spring:
  application:
    name: food-api
  datasource:
    url: jdbc:postgresql://${env.PG_HOST}:${env.PG_PORT}/${env.PG_DATABASE}
    username: ${env.PG_USER}
    password: ${env.PG_PASSWORD}
  http:
    converters:
      preferred-json-mapper: gson
  jpa:
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
server:
  port: ${env.APP_PORT}
  servlet:
    contextPath: /api

flyway:
  url: jdbc:postgresql://${env.PG_HOST}:${env.PG_PORT}/${env.PG_DATABASE}
  user: ${env.PG_USER}
  password: ${env.PG_PASSWORD}
  locations: classpath:db/migration

springfox:
  documentation:
    openApi:
      v3:
        path: /documentation/v3/api-docs
